In [8]:
# Definiendo variables listas en Python
listaNum = [1,2,3,4]
print(listaNum)

[1, 2, 3, 4]


In [18]:
ListaMix = ['Tengo', 1, 'Perro']
print(ListaMix)

['Tengo', 1, 'Perro']


In [19]:
print(ListaMix[0])

Tengo


In [22]:
ListaMix[1] = 3
print(ListaMix)

['Tengo', 3, 'Perro']


In [8]:
ListaDListas=[[1,2,3],[4,5,6],[7,8,9]]
print(ListaDListas)
print(ListaDListas[0][0])
print(ListaDListas[1][:2])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
1
[4, 5]


## Ojo cuando hacen una copia de una de variables en Python

In [2]:

Var1=[1,2]
print('Var1 = ',Var1)
print()

## creando copia de la variable Var1
Var_copy=Var1

# Modificando las copias
Var_copy[0]=3 # Var_copy=[3,2]

print('Mirando los nuevos valores')
print('Var_copy = ',Var_copy)
print('Var1 = ',Var1)


Var1 =  [1, 2]

Mirando los nuevos valores
Var_copy =  [3, 2]
Var1 =  [3, 2]


In [ ]:
Var1=[1,2]
print('Var1 = ',Var1)
print()
Var_copy2=Var1.copy()
Var_copy2[0]=3

print('Mirando los nuevos valores')
print('Var_copy2 = ',Var_copy2)
print('Var1 = ',Var1)

## Numpy arrays

In [9]:
import numpy as np

In [10]:
Matriz=np.array(ListaDListas)
print(Matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
Unos=np.ones([4,3])
print(Unos)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
Ceros=np.zeros([4,3])
print(Ceros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
Rango=np.arange(12)
print(Rango)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
Rango=np.arange(5,12)
print(Rango)

[ 5  6  7  8  9 10 11]


In [29]:
print(Matriz[2,1])

9


In [35]:
print(Matriz[2,0:2])

[7 8]


In [40]:
print(Matriz[:,1:2])

[[2]
 [5]
 [8]]


In [41]:
print(Matriz+2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
print(Matriz>5)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [43]:
print(Matriz[Matriz>5])

[6 7 8 9]


In [58]:
ind=Matriz[1,:]>=5
print(ind)
print(Matriz[1,~ind])

[False  True  True]
[4]
