# Random numbers

In [1]:
# importing random module and numpy
import random
import numpy as np

In [27]:
# Definir la semilla
random.seed(1)

# generar numero aleatorio
r2 = random.random()
print(r2)


# De nuevo
random.seed(1)
# generar numero aleatorio
r2 = random.random()
print(r2)

0.13436424411240122
0.13436424411240122


In [30]:
# Definir la semilla
rgn=np.random.default_rng(seed=1)
print(rgn.random())

# De nuevo
rgn=np.random.default_rng(seed=1)
print(rgn.random())

0.5118216247002567
0.5118216247002567


In [31]:
# imprimir matriz con valores aleatorios entre 0 y 1
print(rgn.random([3,2]))

[[0.9504637  0.14415961]
 [0.94864945 0.31183145]
 [0.42332645 0.82770259]]


In [11]:
r = np.random.randint(10, size=(2, 3))
print(r)

[[5 6 1]
 [1 3 8]]


In [ ]:
choices = np.arange(1,20)
print(choices,'\n')


Sin_rep = np.random.choice(choices,10,replace=False)
print(Sin_rep,'\n')

Con_rep = np.random.choice(choices,10,replace=True)
print(Con_rep,'\n')

# Ejercicios

In [ ]:
# lanzamiento de una moneda
moneda=np.random.randint(1,3, size=(10))
print(moneda)

In [ ]:
# lanzamiento de un dado
dado=np.random.randint(1,6, size=(10))
print(dado)

In [ ]:
# seleccionar alumnos
alumnos=np.arange(1,11)
selected=np.random.choice(alumnos,3,replace=False)
print(selected)

In [25]:
# Dividir grupo de pacientes entre placebo y droga
rgn=np.random.default_rng(seed=1)

pacientes=np.arange(1,11)
print('Todos los pacientes =',pacientes,'\n')


placebo=rgn.choice(pacientes,5,replace=False)
print('Pacientes placebo = ',placebo,'\n')


# crear un vector de booleans del mismo tamaño que pacientes 
#mask=np.array([True,True,True,True,True,True,True,True,True,True])
mask=np.ones(len(pacientes), dtype=bool)

# Marcar todos los indices de los pacientes con placebo como false
mask[placebo-1]=False

# definir el grupo de pacientes que reciben la droga como el grupo inicial menos los del placebo
med=pacientes[mask]

print('Pacientes droga =', med)

Todos los pacientes = [ 1  2  3  4  5  6  7  8  9 10] 

Pacientes placebo =  [4 1 7 9 3] 

Pacientes droga = [ 2  5  6  8 10]
