# Variables and arrays


## Scalars

In [2]:
import numpy as np

## Scalar
A=1;
print(A)

# unit8(1)
B=np.uint8(1)
print(B)

# double(1)
C=np.float64(1)
print(C)

# D=round(1.5)
D=round(1.5)
print(D)



1
1
1.0
2


## Arrays and Matrices

In [32]:
# E=zeros(5,5)
E=np.zeros((5,5))
print(E)

# F=ones(5,5)
F=np.ones((5,5))
print(F)

# G=rand(5,5)
G=np.random.rand(5,5)
print(G)
print()

# H= randi([1,5],3,3)
H=np.random.randint(1,5,(3,3))
print(H)
print()

#I=1:6
I=np.arange(1,7,2)
print(I)
print()

#J=6:1
J=np.flip(np.arange(1,7,2))
print(J)
print()

#K=ones(3,4)'
K=np.transpose(np.ones((3,4)))
print(K)
print()

#L=zeros(5,5); LL=reshape(L,25,1)
L=np.reshape(np.zeros((5,5,)),[25,1])
print(L)

#M=ones(5,5); M=M(:);
M=np.ones((5,5));  M=np.reshape(M,(1,-1))
print(M)

# P=linspace(1,10,5)
P=np.linspace(1,10,5)
print(P)

#O=[[1,2],[3,4,5]]
O=np.concatenate(([1,2],[3,4,5]),axis=0);
print(O)
print()

#P=rand(5,5); save('Var.mat','P')
P=np.random.rand(5,5)
print(P)
print()
np.save('Var.npy',P)
PP=np.load('Var.npy')
print(PP)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.47584161 0.09707933 0.01348524 0.97745639 0.60538843]
 [0.52124208 0.05717235 0.64085582 0.68505471 0.49993069]
 [0.57451317 0.1087451  0.08369763 0.47977077 0.83619237]
 [0.97389927 0.88950454 0.18347118 0.65678596 0.16035038]
 [0.28242178 0.33642793 0.85576428 0.37967077 0.20035282]]

[[2 1 1]
 [2 2 2]
 [4 4 4]]

[1 3 5]

[5 3 1]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]]
[ 1.    3.25  5.5   7.75 10.  ]
[1 2 3 4 5]

[[0.40635073 0.75611269 0.01551453 0.27849883 0.1342927 ]
 [0.77667769 0.30264647 0.66327668 0.02165141 0.5878295 ]
 [0.8074059  0.84649192 0.21338996 0

## Structures

In [35]:
## R.var1=5;
## R.var2=10;
class struct:
    pass
R=struct();
R.var1=5;
R.var2=10;
print(R.var1)

5
