# Variables and arrays


## Scalars

In [ ]:
import numpy as np

## Scalar
A=1;
print(A)

# unit8(1)
B=np.uint8(1)
print(B)

# double(1)
C=np.float64(1)
print(C)

# D=round(1.5)
D=round(1.5)
print(D)



1
1
1.0
2


## Arrays and Matrices

In [ ]:
# E=zeros(5,5)
E=np.zeros((5,5))
print(E)

# F=ones(5,5)
F=np.ones((5,5))
print()
print(F)

# G=rand(5,5)
G=np.random.rand(5,5)
print()
print(G)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0.97910106 0.22811147 0.28126516 0.15776244 0.38164699]
 [0.53887348 0.09212483 0.22933827 0.40136746 0.72469497]
 [0.30361855 0.67513936 0.09764553 0.27951484 0.60867502]
 [0.12150385 0.78711906 0.47524725 0.39235541 0.15600785]
 [0.46769309 0.64335438 0.83385837 0.49963874 0.22039197]]
